### ISSUE TITLE
!start don't work lol

### ISSUE THREAD

**Issue by iDenis124** [RealKC/kingdom-royale-maid#7]

**Comment by RealKC** [comment]
bruh i already fixed that on local

**Comment by Tedyst** [comment]
Just force push lmao

**Comment by RealKC** [comment]
i run this off my pc, i just need to rebuild

**Comment by iDenis124** [comment]
#git channel be vibing rn doe

**Comment by Tedyst** [comment]
And gmail, cuz i get an email for every comment here

**Comment by RealKC** [comment]
absolutely based

**Comment by iDenis124** [comment]
wait this is a real opportunity here

**Comment by iDenis124** [comment]
Sir I am prince from nigeria, I want give you my welth

**Comment by RealKC** [comment]
please don't use my repository to spam people's emails

**Comment by Tedyst** [comment]
> please don't use my repository to spam people's emails

too late

**Comment by RealKC** [comment]
Don't close this before I push commits smh

**Comment by iDenis124** [comment]
didn't you fix it

**Comment by iDenis124** [comment]
ah

**Comment by Tedyst** [comment]
![image](https://user-images.githubusercontent.com/13637623/97909346-c08d3180-1d50-11eb-9875-62a691a349f7.png)
